[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
criterion = { version = "0.5.1" }
winnow = "0.5.19"

[profile.release]
debug = true
lto = true
codegen-units = 1

[[bench]]
name = "day01"
harness = false
